#!/usr/bin/env bash

. Point
. Dot

new Point point1 1 2
point1 print

new Point point2 3 2
point2[y]=4
point2 print

point2 move
point2 print

point2 distance point1 

point2 type

point1 move

echo test copy

point1 print
point2 print

echo copy
# point1=${point2}

point1 print
point2 print

echo move
point1 move

point1 print
point2 print

Point static_method

if (is point1 Point); then
    echo point1 is of class Point
fi

new Dot dot1
new Dot dot2 1 2

Point type dot1

point1 distance dot1

dot1 print
dot2 print

if ! (is dot2 Point); then
    echo dot is not a point!
fi

# point1 distance dot2

