#!/usr/bin/env bash

[ -z $__name__ ] && {
    echo "No identifier passed to constructor! $1 : new" >&2
}

# add intrincic for easier access to methods
eval "$__name__ () { ${this[__class__]} \"\$1\" \"$__name__\" \${@:2}; }"

