#!/usr/bin/env bash

Object() {
    class

    case $__method__ in

        new)
            # add intrincic for access to methods by object name
            eval "$__name__ () { ${this[__class__]} \"\$1\" \"$__name__\" \${@:2}; }"
        ;;

        class)
            echo ${this[__class__]}
        ;;

        is)
            is ${!this} $1
            return $?
        ;;

        destroy)
            unset -f $__name__
            unset $__name__
        ;;

        *)
            . $OOP/no_such_method
        ;;

    esac
}

Object

