#!/usr/bin/env bash

Object() {
    . $OOP/class $@
    . $OOP/scope

    case $__method__ in

        new)
            . $OOP/constructor $@
        ;;

        is)
            is ${!this} $1
            return $?
        ;;

        destroy)
            . $OOP/destroy
        ;;

        *)
            . $OOP/no_such_method
        ;;

    esac
}

Object

