#!/usr/bin/env bash

Object() {
    class

    case $__method__ in

        new)
            . $OOP/constructor $@
        ;;

        class)
            echo ${this[__class__]}
        ;;

        is)
            is ${!this} $1
            return $?
        ;;

        destroy)
            . $OOP/destroy
        ;;

        *)
            . $OOP/no_such_method
        ;;

    esac
}

Object

