#!/usr/bin/env bash

shopt -s expand_aliases

alias class='{ read filler extends class; . $OOP/class $([ "$extends" = "extends" ] && echo extends $class) $@; . $OOP/scope; } <<< "filler" '

. ../oop/Object

new() {
    $1 new ${@:2}
}

is() {
    declare -n this=$1 2>/dev/null

    [ ${this[__class__]} = "$2" ] && return 0

    local __parents__
    read -a __parents__ <<< "${this[__parents__]}"
    for i in ${__parents__[@]}; do
        [ "$i" = "$2" ] && return 0
    done

    return 1
}

