#!/usr/bin/env bash

OOP=../oop

. $OOP/oop

Car() {
    class

    case $__method__ in

        print)
            echo "Beep-beep!"
        ;;
        

        *)
            $Parent $@ 
        ;;

    esac
}

Car

