#!/usr/bin/env bash

OOP=../oop

. $OOP/oop
. ../demo/Point

Dot() {
    . $OOP/class extends Point $@
    . $OOP/scope

    case $__method__ in

        print_of_dot)
            echo "dotprint (${this[x]}; ${this[y]})"
        ;;

        *)
            $Parent $@
        ;;

    esac
}

Dot

