#!/usr/bin/env bash

OOP=../oop

. $OOP/oop

Dot() {
    . $OOP/class extends Object $@
    set -- ${@:3}

    case $__method__ in
        print)
            echo "(${this[x]}; ${this[y]})"
        ;;

        new)
            $Parent $__class__ $@

            this[x]=$1
            this[y]=$2
        ;;

        *)
            $Parent $@
        ;;

    esac
}

