#!/usr/bin/env bash

OOP=../oop
CLASSES=../demo

. $OOP/oop
. $CLASSES/Point

Dot() {
    function f() {
        read class
        . $OOP/class extends $class $@
    }
    local __method__=$1
    local __name__=$2
    . $OOP/scope
    f $__method__ $__name__ $@ <<< Point

    case $__method__ in

        print_of_dot)
            echo "dotprint (${this[x]}; ${this[y]})"
        ;;

        *)
            $Parent $@
        ;;

    esac
}

Dot

